version: "3.8"

services:
  pescarte:
    build:
      context: .
      target: releaser
    container_name: liquid_dev
    command: ["mix", "dev"]
    ports:
      - 4000:4000
    depends_on:
      - database
    env_file:
      - .env-sample
    volumes:
      - .:/src
    environment:
      MIX_ENV: dev
    stdin_open: true
    tty: true

  database:
    image: postgres:14.6
    container_name: liquid_database
    environment:
      - POSTGRES_USER=liquid
      - POSTGRES_PASSWORD=liquid
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquid -d liquid" ]
      interval: 5s
      timeout: 2s
      retries: 1
