app = "redpanda-scti"
primary_region = "gig"

[build]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/var/lib/redpanda/data"
  source = "redpanda_poc"

[http_service]
  internal_port = 29092
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
